FROM cimg/ruby:<%= ruby_version %>-node

ENV PORT=3000
EXPOSE $PORT

COPY --chown=circleci . /home/circleci/project
RUN bundle install --deployment
RUN yarn install --frozen-lockfile

ENV RAILS_ENV=ci

CMD ["./bin/ci-server-start"]
