# Brewfile
# add any dependencies that must be installed from homebrew here

# cloud.gov RDS is on postgres 12
brew "postgresql@12", link: true

# used in bin/with-server script
brew "dockerize"

# used in bin/ops/create_service_account.sh
brew "jq"

# helper scripts for creating new ADRs
brew "adr-tools"

# chromedriver for integration tests
cask "chromedriver"
